#!/usr/bin/python3

# TODO I'm not sure if this is used anymore (or if it ever was)

import getopt
import sys

import lib.date
import lib.fraction
from lib.price import Price
from lib.quotes import Quotes
import lib.stocks

def main():
    (pairs,args) = getopt.getopt(sys.argv[1:],"",["all","email=","date="])
    lookup = dict(pairs)

    nullPrice = Price(1.0,lib.fraction.one)
    quotes = Quotes()

    for c in lib.stocks.companies.values():
        mult = lib.fraction.one
        for r in c.trades:
            mult=r.multAdjust(mult)
        if c.ticker in quotes:
            price = Price(quotes[c.ticker].price,mult)
        else:
            price = nullPrice
        for n in c.notifies:
            if "--all" in lookup or n.isTriggered(price,lib.date.today):
                s = n.lineItem(c,mult)
                if s != "":
                    if "--email" in lookup:
                        n.email(c,mult,lookup["--email"])
                    else:
                        print(s)

main()
