#!/usr/bin/python

import getopt
import os
import string
import sys

import lib.stocks as stocks
import lib.trade as trade
import lib.configuration as configuration

"""
s=tick1+tick2
f=s|1d1t1c1ohgv
e=.csv

"""

def main():

    quote_type = getArgs()
    
    tickers=[]
    if quote_type=="notify":
        target_fname = configuration.NOTIFY_QUOTES_FILE
        for c in stocks.companies.values():
            # find all companies that have ever been bought, or companies
            # that need the price for notification
            if len(c.trades) != 0 \
                    or reduce(lambda r,n: r or n.needsPrice(), c.notifies, 0):
                tickers.append(c.ticker)
    else:
        target_fname = configuration.BUY_SELL_QUOTES_FILE
        for c in stocks.companies.values():
            if c.buy or c.sell:
                tickers.append(c.ticker)

    downloadYahooCsv(tickers,target_fname)

def getArgs():
    if len(sys.argv)==1:
        return "notify"
    validArgs = {"notify":1, "buysell":1}
    if len(sys.argv)==2 and validArgs.has_key(sys.argv[1]):
        return sys.argv[1]
    print "usage: download_quotes ( [ notify | buysell ] )"
    print "default is notify"
    sys.exit(1)

def downloadYahooCsv(tickers,target_fname):
    cmd = "wget -O %s 'http://finance.yahoo.com/d/quotes.csv?s=%s&f=sl1d1t1c1ohgv&e=.csv'" % (configuration.TEMP_FILE, string.join(tickers,"+"))
    doCmd(cmd, 1)
    doCmd("rm "+target_fname, 0)
    doCmd("mv %s %s" % (configuration.TEMP_FILE, target_fname), 1)

def doCmd(cmd,fail):
    input = os.popen(cmd)
    out = input.read()
    ret = input.close()
    print out
    print "ret",ret
    if fail and ret is not None:
        print "error running: "+cmd
        print out
        sys.exit(1)

main()
