#!/usr/bin/python

import cgi
import string
import sys

import stocks

def main():
    
    print "Content-type: text/html\n"

    if len(sys.argv)!=2:
        print "need an argument"
        return
    if sys.argv[1]=="bydate":
        bydate=1
    elif sys.argv[1]=="byticker":
        bydate=0
    else:
        print "arg must be bydate or byticker"
        return

    form = cgi.FieldStorage()

    ticker2olddate = {} # ticker ==> (date,ticker)
    
    for e in stocks.entries:
        if bydate:
            s=e.date
        else:
            s=e.ticker
        if not ticker2olddate.has_key(e.ticker):
            ticker2olddate[e.ticker]=(s,e.date,e.ticker)
        else:
            olddate = ticker2olddate[e.ticker][1]
            if e.date>olddate:
                ticker2olddate[e.ticker]=(s,e.date,e.ticker)

    byDateArg=""
    byTickerArg=""
    if bydate and not form.has_key("reverse"):
        byDateArg="?reverse=1"
    if not bydate and not form.has_key("reverse"):
        byTickerArg="?reverse=1"
        
    print "<p><table>"
    print '<tr><td><a href="bydate.cgi'+byDateArg+'"><b>Date</b></a></td><td><a href="byticker.cgi'+byTickerArg+'"><b>Ticker</b></a></td><td><b>Name</b></td></tr>'

    tups = ticker2olddate.values()
    tups.sort()
    if form.has_key("reverse"):
        tups.reverse()
    if bydate:
        tups.reverse()
    for (s,d,t) in tups:
        link = '<a href="log.cgi?ticker=%s">%s</a>' % \
               (string.lower(cgi.escape(t)),
                cgi.escape(t))
        print "<tr><td>%s</td><td>%s</td><td>%s</td></tr>" % \
              (cgi.escape(d.abbreviated()),
               link,
               cgi.escape(stocks.companies[t].name))

    print "</table>"

main()
