#!/usr/bin/python3 -Wignore

import cgi
import re
import os
import string
import sys
from lib.configuration import LOG_DIR

reTicker = re.compile(r"^[a-z\.]+$")

def main():
    #print("Content-type: text/plain\n")
    print("Content-type: text/html\n")
    form = cgi.FieldStorage()
    if not "ticker" in form:
        print("need ticker argument")
        return
    ticker = str(form["ticker"].value)
    if not reTicker.search(ticker):
        print("invalid ticker: "+ticker)
        return
    disp2(ticker)

def disp1(ticker):
    cmd = "cat %s/%s.txt" % (LOG_DIR,ticker)
    input=os.popen(cmd)
    print(input.read())
    input.close()
    
def disp2(ticker):
    fileName = "%s/%s.txt" % (LOG_DIR,ticker)
    input = open(fileName,'r',encoding='utf-8')
    lineNo = 0
    print("Ticker: "+string.upper(ticker)+"<br><br>")
    while 1:
        line = input.readline()
        lineNo = lineNo + 1
        if line=="":
            break
        print(html.escape(line)+"<br>")
    input.close()

main()
