#!/home/kleemann/opt/bin/python

import lib.stocks as stocks

# TODO: seems kind of useless now that we have unit tests; consider removing

def main():
    for c in stocks.companies.values():
        if len(c.trades)>0:
            print(c.ticker)
            for t in c.trades:
                print(" ",t)

main()
