#!/usr/bin/python

import getopt
import os
import string
import sys

import stocks
import trade

"""
s=tick1+tick2
f=s|1d1t1c1ohgv
e=.csv

"""

def main():

    quote_type = getArgs()
    
    tickers=[]
    if quote_type=="notify":
        for c in stocks.companies.values():
            # find all companies that have ever been bought, or companies
            # that need the price for notification
            if len(c.trades) != 0 \
                    or reduce(lambda r,n: r or n.needsPrice(), c.notifies, 0):
                tickers.append(c.ticker)
    else:
        for c in stocks.companies.values():
            if c.buy or c.sell:
                tickers.append(c.ticker)

    target_fname = "quotes_"+quote_type+".csv"
    cmd = "wget -O new_quotes.csv 'http://finance.yahoo.com/d/quotes.csv?s=%s&f=sl1d1t1c1ohgv&e=.csv'" % string.join(tickers,"+")
    doCmd(cmd,1)
    doCmd("rm "+target_fname,0)
    doCmd("mv new_quotes.csv "+target_fname,1)

def getArgs():
    if len(sys.argv)==1:
        return "notify"
    validArgs = {"notify":1, "buysell":1}
    if len(sys.argv)==2 and validArgs.has_key(sys.argv[1]):
        return sys.argv[1]
    print "usage: download_quotes ( [ notify | buysell ] )"
    print "default is notify"
    sys.exit(1)

def doCmd(cmd,fail):
    input = os.popen(cmd)
    out = input.read()
    ret = input.close()
    print out
    print "ret",ret
    if fail and ret is not None:
        print "error running: "+cmd
        print out
        sys.exit(1)

main()
