#!/usr/bin/python

import getopt
import sys

import stocks

def main():

    optlist, args = getopt.getopt(sys.argv[1:], "trk:")
    opts = {}
    for (opt,val) in optlist:
        opts[opt] = val
    tickerOnly = opts.has_key("-t")
    if opts.has_key("-k"):
        keyword = opts["-k"]
    else:
        keyword = None

    ticker2olddate = {} # ticker ==> (date,ticker)
    
    for e in stocks.entries:
        if not ticker2olddate.has_key(e.ticker):
            ticker2olddate[e.ticker]=(e.date,e.ticker)
        else:
            olddate = ticker2olddate[e.ticker][0]
            if e.date>olddate:
                ticker2olddate[e.ticker]=(e.date,e.ticker)

    tups = ticker2olddate.values()
    tups.sort()
    if opts.has_key("-r"):
        tups.reverse()
    for (d,t) in tups:
        if not keyword or keyword in stocks.companies[t].keywords:
            if tickerOnly:
                print t
            else:
                print "%s %s %s" % \
                    (d.abbreviated(),
                     t,
                     stocks.companies[t].name)

main()

